name: Robot Framework CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Manual trigger

jobs:
  robot-tests:
    runs-on: windows-latest

    steps:
      # 1) Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Install Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Create the Database
      - name: Create the database
        run:  cd ./DB 
              python create_db.py

      # 5) Install browser for Selenium (Chrome)
      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Print Working Directory
        run: pwd

      # 6) Run Robot Tests
      - name: Run Robot Tests
        run: |
          robot -d results tests

      # 7) Upload artifacts (logs + report + screenshots)
      - name: Upload Test Reports
        uses: actions/upload-artifact@v4
        with:
          name: robot-test-results
          path: results/
